services:
  mongodb:
    image: mongo:4.0-xenial
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - /data/db:/data/db
      - /data/configdb:/data/configdb
    ports:
      - "27017:27017"
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

  mongoex:
    image: mongo-express:latest
    container_name: mongoex
    environment:
      - ME_CONFIG_OPTIONS_EDITORTHEME=ambiance
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_BASICAUTH_USERNAME=root
      - ME_CONFIG_BASICAUTH_PASSWORD=password
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
    depends_on:
      mongodb:
        condition: service_healthy
    ports:
      - "8081:8081"

  trudesk:
    image: polonel/trudesk:1
    container_name: trudesk
    environment:
      - NODE_ENV=production
      - TRUDESK_DOCKER=true
      - TD_MONGODB_URI=mongodb://root:password@mongodb:27017/trudesk?authSource=admin
    depends_on:
      mongodb:
        condition: service_healthy
    volumes:
      - /data/trudesk/uploads:/usr/src/trudesk/public/uploads
      - /data/trudesk/plugins:/usr/src/trudesk/plugins
      - /data/trudesk/backups:/usr/src/trudesk/backups
    ports:
      - "8118"

  nginx:
    image: nginx:stable-perl
    container_name: nginx
    volumes:
      - /home/edwin/trudesk/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      trudesk:
        condition: service_started
    ports:
      - "80:80"
